// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import AppHeader from "@/components/navigation/app-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JIYONG IN SOCIAL WALLET",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
}
